Repository GSG-CF04/Coronavirus-API, pull requests merged in 2021-11, with the labels that each got.

#3 Add structure files
  index .html
  script.js
  style.css
Labels: aprove

#4 write To README file
  README.md
Labels: aprove

#11 Create header and Add logo
  img/COVID19- Logo.png
  index .html
  style.css
Labels: awaiting review

#12 add container to bady
  .vscode/settings.json
  index .html
  style.css
Labels: aprove

#13 add fetch, ceate section and card title
  index .html
  script.js
Labels: aprove

#14 crate card body
  script.js
Labels: awaiting review

#15 style container and card
  script.js
  style.css
Labels: aprove

#17 summaryCard
  index .html
  script.js
  style.css
Labels: aprove

#19 createFolder
  index .html
  script/script.js
  style/style.css
Labels: awaiting review

#22 changIndexSpace
  index.html
Labels: awaiting review

#23 deleteOldIndex
  index .html
Labels: awaiting review

#24 addDote
  index.html
Labels: in progress
